apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: sonarqube-pvc
  namespace: sonarqube

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: lvms-vg1

  resources:
    requests:
      storage: 30Gi
