apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgres-secret
  namespace: sonarqube
type: Opaque
stringData:
  POSTGRES_USER: sonar
  POSTGRES_PASSWORD: "SonarDB@123"
  POSTGRES_DB: sonarqube
