apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: sonarqube:/Secret:sonarqube/sonarqube-postgres-secret
  name: sonarqube-postgres-secret
  namespace: sonarqube
type: Opaque
stringData:
  POSTGRES_USER: sonar
  POSTGRES_PASSWORD: "SonarDB@123"
  POSTGRES_DB: sonarqube
